name: Aggregate

on:
  schedule:
    - cron: "0 8 * * *" # 8 a.m. every day UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install requests
    - name: Run aggregator
      run: python3 aggregation/csaf_scraper.py
    - name: Commit updates	
      run: |
        git add .	
        git config user.name "Automated"	
        git config user.email "actions@users.noreply.github.com"	
        git commit -m "csaf updates" 	
    - name: Push	
      run: git push
